apiVersion: v1
kind: Service
metadata:
  labels:
    app: {{ app_name }}
  name: {{ service_name }}
spec:
  type: LoadBalancer
  ports:
  - port: 80
    protocol: TCP
    targetPort: 3000
  selector:
    app: {{ app_name }}